name: 新機能の追加
description: 新しい機能や改善を追加したい場合に使用してください
title: "[新機能] "
labels: ["enhancement", "teacher-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## 新機能追加リクエスト
        
        このフォームを使って、学校管理システムに新しい機能を追加したいときの詳細を教えてください。
        技術的な知識は不要です。どのような機能が欲しいか、なぜ必要かを具体的に説明してください。

  - type: input
    id: feature_name
    attributes:
      label: 機能名
      description: 追加したい機能の名前（例：「新しい部活動の追加」「出席管理機能」）
      placeholder: 例：英会話クラブの登録機能
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: 現在の問題・状況
      description: なぜこの機能が必要ですか？現在どのような不便さや問題がありますか？
      placeholder: |
        例：
        - 現在、新しい部活動を追加するのに手間がかかる
        - 学生が自分で登録できる仕組みがない
        - 部活動の定員管理ができない
    validations:
      required: true

  - type: textarea
    id: desired_functionality
    attributes:
      label: 欲しい機能の詳細
      description: どのような機能が欲しいですか？具体的に説明してください
      placeholder: |
        例：
        - 教師が新しい部活動を簡単に追加できる画面
        - 学生が一覧から部活動を選んで登録できる機能
        - 定員に達したら自動的に募集を停止する機能
        - 登録済み学生のリストを確認できる機能
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 成功の基準
      description: この機能ができたとき、何ができれば成功と言えますか？
      placeholder: |
        例：
        - 教師が3クリック以内で新しい部活動を追加できる
        - 学生が部活動に登録して確認メールを受け取れる
        - 定員オーバーの場合、適切なメッセージが表示される
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: 主に使用するユーザー
      description: この機能を主に使うのは誰ですか？
      options:
        - 教師
        - 学生
        - 両方
        - 管理者
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の緊急度はどの程度ですか？
      options:
        - 高（今すぐ必要）
        - 中（近いうちに必要）
        - 低（あったら便利）
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 追加の情報・制限事項
      description: その他、開発時に考慮すべき点があれば教えてください
      placeholder: |
        例：
        - 既存の学生データと連携する必要がある
        - 特定の時期（新学期など）に合わせてリリースしたい
        - 他の先生も同様の要望を持っている
        - セキュリティに注意が必要（学生の個人情報を扱う）

  - type: checkboxes
    id: implementation_hints
    attributes:
      label: 実装のヒント（開発者向け）
      description: 以下の項目で該当するものをチェックしてください
      options:
        - label: データベースの変更が必要そう
        - label: 新しいページ・画面の作成が必要
        - label: 既存の画面の改修が必要
        - label: メール送信機能が必要
        - label: ユーザー権限の管理が必要
        - label: API エンドポイントの追加が必要

  - type: textarea
    id: suggested_solution
    attributes:
      label: 開発者向けのヒント・提案
      description: |
        この機能を実装するために役立つ技術的なヒントです：
        
        **注意事項:**
        - HTML、CSS、JavaScript、Pythonのみ使用
        - 既存のFastAPIアーキテクチャを維持
        - データベース操作はdatabase.pyを使用
        - フロントエンドはstatic/index.htmlを拡張
        - 新しいAPIエンドポイントはroutersディレクトリに追加
        - ユーザーエクスペリエンスをシンプルに保つ
        - 技術に詳しくない教師・学生でも使いやすく設計
      render: markdown