name: 画面・操作性の改善
description: システムの見た目や使いやすさを改善したい場合に使用してください
title: "[UI改善] "
labels: ["ui/ux", "improvement", "teacher-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## 画面・操作性の改善リクエスト
        
        システムの画面や操作性を改善したい場合、このフォームを使って詳細を教えてください。
        どの部分が使いにくいか、どのように改善したいかを具体的に説明してください。

  - type: input
    id: improvement_area
    attributes:
      label: 改善したい部分
      description: どの画面や機能の改善を希望しますか？
      placeholder: 例：ログイン画面、部活動一覧、登録フォーム、メニューナビゲーション
    validations:
      required: true

  - type: textarea
    id: current_problem
    attributes:
      label: 現在の使いにくさ
      description: 現在の画面や操作のどの部分が使いにくいですか？
      placeholder: |
        例：
        - ボタンが小さくて押しにくい
        - 文字が小さくて読みにくい
        - どこをクリックすればいいかわからない
        - 画面が見つけにくい場所にある
        - 操作の手順がわかりにくい
    validations:
      required: true

  - type: textarea
    id: desired_improvement
    attributes:
      label: 希望する改善内容
      description: どのように改善されると使いやすくなりますか？
      placeholder: |
        例：
        - ボタンを大きくしてほしい
        - 文字サイズを大きくしてほしい
        - 色を変えてわかりやすくしてほしい
        - メニューの配置を変えてほしい
        - 操作手順を簡単にしてほしい
    validations:
      required: true

  - type: dropdown
    id: affected_users
    attributes:
      label: 主に影響を受けるユーザー
      description: この改善は主にどのユーザーに役立ちますか？
      options:
        - 教師
        - 学生
        - 両方
        - 管理者
        - 全てのユーザー
    validations:
      required: true

  - type: dropdown
    id: device_type
    attributes:
      label: 主に使用するデバイス
      description: この改善が特に必要なデバイスはありますか？
      options:
        - パソコン
        - タブレット
        - スマートフォン
        - 全てのデバイス
        - 不明
    validations:
      required: true

  - type: checkboxes
    id: improvement_type
    attributes:
      label: 改善の種類
      description: どのような改善を希望しますか？（複数選択可）
      options:
        - label: 色・デザインの改善
        - label: 文字サイズ・フォントの改善
        - label: ボタン・リンクの改善
        - label: レイアウト・配置の改善
        - label: ナビゲーション・メニューの改善
        - label: 操作手順の簡素化
        - label: エラーメッセージの改善
        - label: 表示速度の改善

  - type: textarea
    id: success_criteria
    attributes:
      label: 改善の成功基準
      description: どうなったら改善されたと言えますか？
      placeholder: |
        例：
        - 新しい教師でも迷わずに操作できる
        - 学生が1分以内に部活動に登録できる
        - スマートフォンでも快適に使える
        - 操作ミスが減る
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この改善の緊急度はどの程度ですか？
      options:
        - 高（すぐに改善したい）
        - 中（近いうちに改善したい）
        - 低（あったら良い）
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 追加の情報
      description: 他に参考になる情報があれば教えてください
      placeholder: |
        例：
        - 他の学校のシステムで良いと思った機能がある
        - 学生や他の教師からの要望がある
        - 特定の年齢層に配慮が必要
        - アクセシビリティ（障害者対応）への配慮が必要

  - type: textarea
    id: design_references
    attributes:
      label: 参考例・イメージ
      description: 参考になるウェブサイトやアプリがあれば教えてください
      placeholder: |
        例：
        - 〇〇学校のウェブサイトのような感じ
        - Googleのような分かりやすいデザイン
        - スマートフォンアプリの〇〇のような操作感
        - 現在の〇〇部分を〇〇のように変更

  - type: textarea
    id: technical_guidance
    attributes:
      label: 開発者向けガイダンス
      description: |
        **UI/UX改善のための技術的な指針:**
        
        **フロントエンド制約:**
        - HTML、CSS、JavaScriptのみ使用
        - レスポンシブデザイン対応（PC、タブレット、スマートフォン）
        - アクセシビリティ基準の遵守
        - シンプルで直感的なインターフェース
        
        **既存ファイル:**
        - `src/static/index.html` - メインHTMLファイル
        - `src/static/styles.css` - スタイルシート
        - `src/static/app.js` - JavaScriptロジック
        
        **デザイン原則:**
        - 技術に不慣れなユーザーを想定
        - 最小限のクリック数で目標達成
        - 明確な視覚的ヒント・フィードバック
        - 一貫性のあるデザイン言語
        - エラー時の分かりやすいメッセージ
      render: markdown